services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      node.name: 'es01'
      cluster.name: 'docker-cluster'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'false'
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_API_ADDR: http://vault:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    command: vault server -config /vault/config/vault.json

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - node.name=kibana
      - cluster.name=docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: ai-backend:latest
    container_name: backend
    restart: always
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
      - celery_gmail
      - celery_telegram
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1

      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VAULT_ADDR=http://vault:8200
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
  
  celery_gmail:
    image: ai-backend:latest
    container_name: celery_gmail
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=30 -Q gmail_process --loglevel=info
    depends_on:
      - elasticsearch
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VAULT_ADDR=http://vault:8200

  celery_telegram:
    image: ai-backend:latest
    container_name: celery_telegram
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=30 -Q telegram_process --loglevel=info
    depends_on:
      - elasticsearch
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - VAULT_ADDR=http://vault:8200

volumes:
  esdata:

