version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - dokploy-network
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 800M

  vault:
    image: hashicorp/vault:latest
    restart: always
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - dokploy-network
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/config/vault-sa.json:/vault/config/vault-sa.json
    command: vault server -config /vault/config/vault.hcl

  redis:
    image: redis:alpine
    restart: always
    networks:
      - dokploy-network

  backend:
    build: .
    restart: always
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - celery_gmail
      - celery_telegram
      - elasticsearch
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      VAULT_ADDR: ${VAULT_ADDR}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backendsearch.fahdbahri.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certResolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  celery_gmail:
    build: .
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=10 -Q gmail_process --loglevel=info
    depends_on:
      - redis
      - elasticsearch
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      VAULT_ADDR: ${VAULT_ADDR}
    networks:
      - dokploy-network

  celery_telegram:
    build: .
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=10 -Q telegram_process --loglevel=info
    depends_on:
      - redis
      - elasticsearch
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      VAULT_ADDR: ${VAULT_ADDR}
    networks:
      - dokploy-network

volumes:
  esdata:

networks:
  dokploy-network:
    external: true
