version: "2.9"  # Or "3.8", "3.7" — depending on your Docker version

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      node.name: 'es01'
      cluster.name: 'docker-cluster'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - appnet


  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    networks:
      - appnet
    command: vault server -config /vault/config/vault.json

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - node.name=kibana
      - cluster.name=docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  rabbitmq_data:
  esdata:

networks:
  appnet:
