services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/config/vault-sa.json:/vault/config/vault-sa.json
    networks:
      - dokploy-network
    command: vault server -config /vault/config/vault.hcl

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dokploy-network

  backend:
    build: .
    container_name: backend
    restart: always
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - celery_gmail
      - celery_telegram
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - VAULT_ADDR=http=${VAULT_ADDR}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.search.fahdbahri.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.next-app.tls.certResolver=letsencrypt"
      - "traefik.http.routers.backend.loadbalancer.server.port=8000"
  
  celery_gmail:
    build: .
    container_name: celery_gmail
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=30 -Q gmail_process --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - VAULT_ADDR=${VAULT_ADDR}
    networks:
      - dokploy-network

  celery_telegram:
    build: .
    container_name: celery_telegram
    restart: always
    command: uv run celery -A services.celery_config:celery_app worker --pool=threads --concurrency=30 -Q telegram_process --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - VAULT_ADDR=${VAULT_ADDR}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: bridge
